version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongo-nest-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
volumes:
  mongodbdata: